# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-28 03:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porte', models.CharField(choices=[(b'pequeno', b'Pequeno'), (b'medio', b'Medio'), (b'grande', b'Grande')], default=b'pequeno', max_length=8)),
                ('nome', models.CharField(default=b'nome', max_length=15)),
                ('raca', models.CharField(default=b'raca', max_length=15)),
                ('sexo', models.CharField(choices=[(b'F', b'Femea'), (b'M', b'Macho')], default=b'Macho', max_length=1)),
                ('foto', models.ImageField(default=b'/uploads/padrao.jpg', upload_to=main.models.user_directory_path)),
                ('bio', models.TextField(default=b'bio', max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
