# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-11 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171107_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='sexo',
            field=models.CharField(choices=[(b'F', b'F\xc3\xaamea'), (b'M', b'Macho')], default=b'Macho', max_length=1),
        ),
    ]
