# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-11 16:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20171111_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user1status', models.CharField(choices=[(b'A', b'Aprovado'), (b'R', b'Rejeitado'), (b'N', b'NaoAvaliado')], default=b'NaoAvaliado', max_length=1)),
                ('user2status', models.CharField(choices=[(b'A', b'Aprovado'), (b'R', b'Rejeitado'), (b'N', b'NaoAvaliado')], default=b'NaoAvaliado', max_length=1)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('data',),
            },
        ),
    ]
