# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-12 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_profile_qntcomb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='foto',
            field=models.ImageField(default=b'/home/ubuntu/workspace/uploads/padrao.jpg', upload_to=main.models.user_directory_path),
        ),
    ]
