# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-12 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20171112_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='celular',
            field=models.CharField(default=b'000000000', max_length=9),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ddd',
            field=models.CharField(default=b'00', max_length=2),
        ),
    ]
