# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-12 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20171112_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rua',
            field=models.CharField(help_text=b'Digite seu endere\xc3\xa7o e confira o local no mapa', max_length=255),
        ),
    ]
