# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-17 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20171117_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='distancia',
            field=models.FloatField(default=b'999999999'),
        ),
    ]
