# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-18 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_match_distancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cadastrouPet',
            field=models.BooleanField(default=False),
        ),
    ]
