# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-19 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_profile_cadastroupet'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaleConosco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('assunto', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mensagem', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='mesmaRaca',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='rangeBusca',
            field=models.IntegerField(default=b'20'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='raca',
            field=models.CharField(choices=[(b'affenpinscher', b'Affenpinscher'), (b'airedale_terrier', b'Airedale Terrier'), (b'akita_inu', b'Akita Inu'), (b'basset_hound', b'Basset Hound'), (b'beagle', b'Beagle'), (b'bichon_frise', b'Bichon Fris\xc3\xa9'), (b'boiadeiro_australiano', b'Boiadeiro Australiano'), (b'boiadeiro_de_berna', b'Boiadeiro de Berna'), (b'border_collie', b'Border Collie'), (b'boston_terrier', b'Boston Terrier'), (b'boxer', b'Boxer'), (b'buldogue', b'Buldogue'), (b'buldogue_frances', b'Buldogue Franc\xc3\xaas'), (b'bull_terrier', b'Bull Terrier'), (b'bulmastife', b'Bulmastife'), (b'chihuahua', b'Chihuahua'), (b'chow_chow', b'Chow Chow'), (b'cocker_spaniel', b'Cocker Spaniel'), (b'corgi', b'Corgi'), (b'dachshund', b'Dachshund'), (b'dobermann', b'Dobermann'), (b'dogue_alemao', b'Dogue Alem\xc3\xa3o'), (b'galgo_ingles', b'Galgo Ingl\xc3\xaas'), (b'golden_retriever', b'Golden Retriever'), (b'husky_siberiano', b'Husky Siberiano'), (b'labrador_retriever', b'Labrador Retriever'), (b'lhasa_apso', b'Lhasa Apso'), (b'malamute_do_alasca', b'Malamute do Alasca'), (b'maltes', b'Malt\xc3\xaas'), (b'mastim_ingles', b'Mastim Ingl\xc3\xaas'), (b'norwich_terrier', b'Norwich Terrier'), (b'pastor_alemao', b'Pastor Alem\xc3\xa3o'), (b'pastor_australiano', b'Pastor Australiano'), (b'pastor_belga', b'Pastor Belga'), (b'pastor_de_shetland', b'Pastor de Shetland'), (b'pastor_ingles', b'Pastor Ingl\xc3\xaas'), (b'pequines', b'Pequin\xc3\xaas'), (b'pit_bull', b'Pit Bull'), (b'pointer_ingles', b'Pointer Ingl\xc3\xaas'), (b'poodle', b'Poodle'), (b'pug', b'Pug'), (b'raca_desconhecida', b'Ra\xc3\xa7a Desconhecida'), (b'rottweiler', b'Rottweiler'), (b'saluki', b'Saluki'), (b'sao_bernardo', b'S\xc3\xa3o Bernardo'), (b'shiba_inu', b'Shiba Inu'), (b'shih_tzu', b'Shih Tzu'), (b'spitz_alemao', b'Spitz Alem\xc3\xa3o'), (b'terra_nova', b'Terra Nova'), (b'yorkshire_terrier', b'Yorkshire Terrier')], default=b'raca_desconhecida', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rua',
            field=models.CharField(help_text=b'Digite seu endere\xc3\xa7o e ajuste o local no mapa caso necess\xc3\xa1rio', max_length=255),
        ),
    ]
