# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-19 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20171117_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rangeBusca',
            field=models.IntegerField(default=b'20'),
        ),
    ]
