# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-21 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20171119_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='vista',
            field=models.BooleanField(default=False),
        ),
    ]
