# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-21 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_mensagem_vista'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='naoVistas',
            field=models.IntegerField(default=b'0'),
        ),
    ]
