# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-19 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_profile_rangebusca'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mesmaRaca',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rua',
            field=models.CharField(help_text=b'Digite seu endere\xc3\xa7o e ajuste o local no mapa caso necess\xc3\xa1rio', max_length=255),
        ),
    ]
